### ISSUE TITLE
Update live demo url

### ISSUE THREAD

**Issue by kimhnh** [devchallenges-io/web-project-ideas#4]
Hi, I was wondering if the website supports updating the live demo URL after submitting a solution. I could only change the title and description on its form.

**Comment by nghiemthu** [comment]
@kimhnh You can achieve the solution and re-upload, then you can change the demo URL, as the solution demo URL needs to be compared to the design

**Comment by kimhnh** [comment]
Thanks, I'll try that! Also thank you for the challenges, they have been very helpful.
